<?php

declare(strict_types=1);

namespace Dysback\Ogo\Database;

/**
 * Abstract base class for database connection implementations.
 *
 * Holds the PDO instance and provides shared prepared-statement logic
 * that concrete drivers inherit.
 */
abstract class BaseDatabase implements IDatabase
{
    /** @var \PDO The underlying PDO connection. */
    protected \PDO $pdo;

    /**
     * Prepares and executes a SQL query, returning the statement.
     *
     * @param string $sql    SQL query with optional positional (?) placeholders.
     * @param array  $params Values to bind to the placeholders.
     *
     * @return \PDOStatement The executed statement.
     */
    public function query(string $sql, array $params = []): \PDOStatement
    {
        $stmt = $this->pdo->prepare($sql);
        $stmt->execute($params);

        return $stmt;
    }

    /**
     * Executes a SQL statement that does not return rows.
     *
     * @param string $sql    SQL statement with optional positional (?) placeholders.
     * @param array  $params Values to bind to the placeholders.
     *
     * @return bool True on success.
     */
    public function execute(string $sql, array $params = []): bool
    {
        $stmt = $this->pdo->prepare($sql);

        return $stmt->execute($params);
    }

    /**
     * Executes a SELECT query and returns all matching rows.
     *
     * @param string $sql    SQL query with optional positional (?) placeholders.
     * @param array  $params Values to bind to the placeholders.
     *
     * @return array An array of associative arrays representing the result rows.
     */
    public function fetchAll(string $sql, array $params = []): array
    {
        return $this->query($sql, $params)->fetchAll();
    }

    /**
     * Executes a SELECT query and returns the first matching row.
     *
     * @param string $sql    SQL query with optional positional (?) placeholders.
     * @param array  $params Values to bind to the placeholders.
     *
     * @return array|false An associative array for the row, or false if no row found.
     */
    public function fetch(string $sql, array $params = []): array|false
    {
        $result = $this->query($sql, $params)->fetch();

        return $result === false ? false : $result;
    }

    /**
     * Returns the ID generated by the last INSERT statement.
     *
     * @return string|false The last insert ID, or false if not available.
     */
    public function lastInsertId(): string|false
    {
        return $this->pdo->lastInsertId();
    }
}
