<?php

declare(strict_types=1);

namespace Dysback\Ogo\Database;

/**
 * Interface for database connection implementations.
 *
 * Provides a consistent API for executing SQL queries and fetching results,
 * independent of the underlying database driver.
 */
interface IDatabase
{
    /**
     * Prepares and executes a SQL query, returning the statement for further use.
     *
     * @param string  $sql    The SQL query with optional positional (?) placeholders.
     * @param array   $params Values to bind to the placeholders.
     *
     * @return \PDOStatement The executed statement.
     */
    public function query(string $sql, array $params = []): \PDOStatement;

    /**
     * Executes a SQL statement that does not return rows (INSERT, UPDATE, DELETE).
     *
     * @param string  $sql    The SQL statement with optional positional (?) placeholders.
     * @param array   $params Values to bind to the placeholders.
     *
     * @return bool True on success, false on failure.
     */
    public function execute(string $sql, array $params = []): bool;

    /**
     * Executes a SELECT query and returns all matching rows.
     *
     * @param string  $sql    The SQL query with optional positional (?) placeholders.
     * @param array   $params Values to bind to the placeholders.
     *
     * @return array An array of associative arrays representing the result rows.
     */
    public function fetchAll(string $sql, array $params = []): array;

    /**
     * Executes a SELECT query and returns the first matching row.
     *
     * @param string  $sql    The SQL query with optional positional (?) placeholders.
     * @param array   $params Values to bind to the placeholders.
     *
     * @return array|false An associative array for the row, or false if no row found.
     */
    public function fetch(string $sql, array $params = []): array|false;

    /**
     * Returns the ID generated by the last INSERT statement.
     *
     * @return string|false The last insert ID as a string, or false if not available.
     */
    public function lastInsertId(): string|false;
}
